version: '3.7'

services:
  postgres:
    image: public.ecr.aws/peakon/postgres
    restart: always
    environment:
      POSTGRES_DB: cooking
      POSTGRES_USER: em
      POSTGRES_PASSWORD: em
    ports:
      - 5432:5432
    networks:
      - dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  dev:
